# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\api_login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiLogin(HttpRunner):

    config = (
        Config("test case 1")
        .base_url("http://api.keyou.site:8000")
        .verify(False)
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/user/login/")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "$username", "password": "$password"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseApiLogin().test_start()
